# SPDX-License-Identifier: GPL-2.0 OR Linux-OpenIB
# SPDX-FileCopyrightText: Copyright (C) 2018-2024 Advanced Micro Devices, Inc.

clean-files += autocompat.h* .kpath

ifeq ($(CONFIG_INFINIBAND),)
$(warning ****** Skipping IONIC RDMA driver; CONFIG_INFINIBAND not set ******)
else ifeq ($(CONFIG_AUXILIARY_BUS),)
$(warning ****** Skipping IONIC RDMA driver; CONFIG_AUXILIARY_BUS not set ******)
else
ccflags-y := -I$(src)/uapi
# upstream version
# ccflags-y +=  -I $(srctree)/drivers/net/ethernet/pensando/ionic

obj-$(CONFIG_INFINIBAND_IONIC)	+= ionic_rdma.o

ionic_rdma-y :=	\
	ionic_ibdev.o ionic_queue.o ionic_sysfs.o \
	ionic_controlpath.o ionic_datapath.o \
	ionic_admin.o ionic_pgtbl.o ionic_hw_stats.o \
	ionic_dcqcn.o ionic_res.o

srcroot ?= $(src)/../../..
export OFA_KSRC ?= /usr/src/ofa_kernel/default
include $(srcroot)/etc/autocompat.mk
$(addprefix $(obj)/,$(ionic_rdma-y)): $(src)/autocompat.h
$(obj)/ionic_rdma.o: $(src)/autocompat.h
endif
