/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2018, Pensando Systems Inc.
 */

#ifndef PCIEIND_REASON_DEF
#define PCIEIND_REASON_DEF(NAME, VAL)
#endif

PCIEIND_REASON_DEF(RSRV0, 0)
PCIEIND_REASON_DEF(RSRV1, 1)
PCIEIND_REASON_DEF(MSG, 2)
PCIEIND_REASON_DEF(UNSUPPORTED, 3)
PCIEIND_REASON_DEF(PMV, 4)
PCIEIND_REASON_DEF(DBPMV, 5)
PCIEIND_REASON_DEF(ATOMIC, 6)
PCIEIND_REASON_DEF(PMTMISS, 7)
PCIEIND_REASON_DEF(PMRMISS, 8)
PCIEIND_REASON_DEF(PRTMISS, 9)
PCIEIND_REASON_DEF(DBF2VFIDMISS, 10)
PCIEIND_REASON_DEF(PRTOOR, 11)
PCIEIND_REASON_DEF(VFIDOOR, 12)
PCIEIND_REASON_DEF(BDFOOR, 13)
PCIEIND_REASON_DEF(PMRIND, 14)
PCIEIND_REASON_DEF(PRTIND, 15)
PCIEIND_REASON_DEF(PMRECC, 16)
PCIEIND_REASON_DEF(PRTECC, 17)

#undef PCIEIND_REASON_DEF
