/* SPDX-License-Identifier: GPL-2.0 */
/*
 * Copyright (c) 2021-2022, Pensando Systems Inc.
 */

#ifndef __ASIC_REGS_ELBA_H__
#define __ASIC_REGS_ELBA_H__

#ifdef __cplusplus
extern "C" {
#if 0
} /* close to calm emacs autoindent */
#endif
#endif

#define ASIC_(REG)      ELB_ ##REG
#define PXB_(REG) \
    (ELB_ADDR_BASE_PXB_PXB_OFFSET + ELB_PXB_CSR_ ##REG## _BYTE_ADDRESS)
#define _PXC_BASE(pn) \
    (ELB_ADDR_BASE_PP_PXC_0_OFFSET + \
     ((pn) * ELB_ADDR_BASE_PP_PXC_0_SIZE))
#define PXC_(REG, pn) \
    (_PXC_BASE(pn) + ELB_PXC_CSR_ ##REG## _BYTE_ADDRESS)

/* elb_top_csr_defines.h */
#define ELB_ADDR_BASE_PXB_PXB_OFFSET 0x20000000
#define ELB_ADDR_BASE_PP_PXC_0_OFFSET 0x20100000
#define ELB_ADDR_BASE_PP_PXC_0_SIZE 0x40000
#define ELB_ADDR_BASE_INTR_INTR_OFFSET 0x61800000

/* elb_pxb_c_hdr.h */
#define ELB_PXB_CSR_DHS_TGT_NOTIFY_BYTE_ADDRESS 0xc4000
#define ELB_PXB_CSR_DHS_ITR_PCIHDRT_BYTE_ADDRESS 0x8000
#define ELB_PXB_CSR_DHS_TGT_PMT_BYTE_ADDRESS 0x18000
#define ELB_PXB_CSR_DHS_TGT_PMR_BYTE_ADDRESS 0x20000
#define ELB_PXB_CSR_DHS_TGT_PRT_BYTE_ADDRESS 0x30000
#define ELB_PXB_CSR_DHS_TGT_AXIMST0_BYTE_ADDRESS 0x62000
#define ELB_PXB_CSR_DHS_TGT_AXIMST1_BYTE_ADDRESS 0x63000
#define ELB_PXB_CSR_DHS_TGT_IND_RSP_ENTRY_BYTE_ADDRESS 0xc4020
#define ELB_PXB_CSR_CFG_TGT_REQ_NOTIFY_INT_BYTE_ADDRESS 0xc4160
#define ELB_PXB_CSR_CFG_TGT_REQ_NOTIFY_RING_SIZE_BYTE_ADDRESS 0xc4170
#define ELB_PXB_CSR_CFG_TGT_REQ_INDIRECT_INT_BYTE_ADDRESS 0xc4180
#define ELB_PXB_CSR_CFG_TGT_NOTIFY_EN_BYTE_ADDRESS 0xc41c4
#define ELB_PXB_CSR_CFG_TGT_PMT_GRST_BYTE_ADDRESS 0xc4244
#define ELB_PXB_CSR_STA_TGT_IND_INFO_BYTE_ADDRESS 0xc43c0
#define ELB_PXB_CSR_DHS_ITR_PCIHDRT_ENTRIES 0x800
#define ELB_PXB_CSR_DHS_ITR_PCIHDRT_ENTRY_BYTE_SIZE 0x10
#define ELB_PXB_CSR_DHS_TGT_PMT_ENTRY_ARRAY_ELEMENT_SIZE 0x1
#define ELB_PXB_CSR_DHS_TGT_PMR_ENTRY_BYTE_SIZE 0x10
#define ELB_PXB_CSR_DHS_TGT_PRT_ENTRY_BYTE_SIZE 0x10

/* elb_pxc_c_hdr.h */
#define ELB_PXC_CSR_DHS_C_MAC_APB_ENTRY_BYTE_ADDRESS 0x1000

/* elb_intr_c_hdr.h */
#define ELB_INTR_CSR_DHS_INTR_ASSERT_ENTRY_ARRAY_COUNT 0x2000
#define ELB_INTR_CSR_DHS_INTR_MSIXCFG_BYTE_OFFSET 0x20000
#define ELB_INTR_CSR_DHS_INTR_FWCFG_BYTE_OFFSET 0x40000
#define ELB_INTR_CSR_DHS_INTR_DRVCFG_BYTE_OFFSET 0x80000
#define ELB_INTR_CSR_DHS_INTR_ASSERT_BYTE_OFFSET 0xd0000
#define ELB_INTR_CSR_DHS_INTR_STATE_BYTE_OFFSET 0xe0000

#define HDRT_BASE       PXB_(DHS_ITR_PCIHDRT)
#define HDRT_COUNT      ASIC_(PXB_CSR_DHS_ITR_PCIHDRT_ENTRIES)
#define HDRT_STRIDE     ASIC_(PXB_CSR_DHS_ITR_PCIHDRT_ENTRY_BYTE_SIZE)
#define HDRT_NWORDS     3

#define IND_INFO_BASE   PXB_(STA_TGT_IND_INFO)
#define IND_INFO_NWORDS 1
#define IND_INFO_STRIDE 4

#define AXIMST_BASE     PXB_(DHS_TGT_AXIMST0)
#define AXIMST_STRIDE   \
    (ASIC_(PXB_CSR_DHS_TGT_AXIMST1_BYTE_ADDRESS) - \
     ASIC_(PXB_CSR_DHS_TGT_AXIMST0_BYTE_ADDRESS))

#define AXIS_INFO_BYTE_COUNT    16
#define AXIMST_NWORDS           4
#define AXIMST_ENTRY_STRIDE     32
#define AXIMST_ENTRIES_PER_PORT 16
#define AXIMST_PORTS_PER_ROW    8
#define AXIMST_PORT_STRIDE      (AXIMST_ENTRY_STRIDE * AXIMST_ENTRIES_PER_PORT)

#define IND_RSP_ADDR    PXB_(DHS_TGT_IND_RSP_ENTRY)
#define IND_RSP_NWORDS  5

#define IND_INT_ADDR    PXB_(CFG_TGT_REQ_INDIRECT_INT)

#define INTR_BASE               ASIC_(ADDR_BASE_INTR_INTR_OFFSET)
#define INTR_COUNT              ASIC_(INTR_CSR_DHS_INTR_ASSERT_ENTRY_ARRAY_COUNT)

#define INTR_MSIXCFG_OFFSET     ASIC_(INTR_CSR_DHS_INTR_MSIXCFG_BYTE_OFFSET)
#define INTR_MSIXCFG_BASE(i)    (INTR_BASE + INTR_MSIXCFG_OFFSET)
#define INTR_MSIXCFG_STRIDE     0x10

#define INTR_FWCFG_OFFSET       ASIC_(INTR_CSR_DHS_INTR_FWCFG_BYTE_OFFSET)
#define INTR_FWCFG_BASE(i)      (INTR_BASE + INTR_FWCFG_OFFSET)
#define INTR_FWCFG_STRIDE       0x8

#define INTR_DRVCFG_OFFSET      ASIC_(INTR_CSR_DHS_INTR_DRVCFG_BYTE_OFFSET)
#define INTR_DRVCFG_BASE(i)     (INTR_BASE + INTR_DRVCFG_OFFSET)
#define INTR_DRVCFG_STRIDE      0x20

#define INTR_ASSERT_OFFSET      ASIC_(INTR_CSR_DHS_INTR_ASSERT_BYTE_OFFSET)
#define INTR_ASSERT_BASE(i)     (INTR_BASE + INTR_ASSERT_OFFSET)
#define INTR_ASSERT_STRIDE      0x4
#define INTR_ASSERT_DATA        0x00000001 /* in little-endian */

#define INTR_STATE_OFFSET       ASIC_(INTR_CSR_DHS_INTR_STATE_BYTE_OFFSET)
#define INTR_STATE_BASE(i)      (INTR_BASE + INTR_STATE_OFFSET)
#define INTR_STATE_STRIDE       0x10

#define NOTIFY_EN               PXB_(CFG_TGT_NOTIFY_EN)
#define NOTIFY_RING_SIZE        PXB_(CFG_TGT_REQ_NOTIFY_RING_SIZE)

#define NOTIFY_BASE             PXB_(DHS_TGT_NOTIFY)
#define NOTIFY_STRIDE           4

#define NOTIFY_INT_ADDR         PXB_(CFG_TGT_REQ_NOTIFY_INT)

#define PMT_BASE                PXB_(DHS_TGT_PMT)
#define PMT_STRIDE      \
    (ASIC_(PXB_CSR_DHS_TGT_PMT_ENTRY_ARRAY_ELEMENT_SIZE) * 4 * 8)
#define PMT_GRST                PXB_(CFG_TGT_PMT_GRST)
#define PMR_BASE                PXB_(DHS_TGT_PMR)
#define PMR_STRIDE              ASIC_(PXB_CSR_DHS_TGT_PMR_ENTRY_BYTE_SIZE)

#define PRT_BASE        PXB_(DHS_TGT_PRT)
#define PRT_STRIDE      ASIC_(PXB_CSR_DHS_TGT_PRT_ENTRY_BYTE_SIZE)

/* the only client freeing slabs is overrides */
#define PRT_SLAB_SIZE   PCIEHDEVICE_OVERRIDE_INTRGROUPS

#ifdef __cplusplus
}
#endif

#endif /* __ASIC_REGS_ELBA_H__ */
